apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-java-app.fullname" . }}
  labels:
    {{- include "simple-java-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-java-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "simple-java-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          env:
            - name: APP_PORT
              value: {{ .Values.appPort | quote }}
          {{- range $key, $value := .Values.configMap.data }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.secrets.enabled }}
          {{- range $key, $value := .Values.secrets.data }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ include "simple-java-app.fullname" $ }}-secrets
                key: {{ $key }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 10 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 10 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}